### ISSUE TITLE
no longer builds on python 3.9+

### ISSUE THREAD

**Issue by glyph** [ronaldoussoren/pyobjc-masshortcut#1]
```
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/yl/ndrrqv712fs02p5sdtxhml7h0000gn/T/pip-install-k6y5qymk/pyobjc-masshortcut_e3ef160adc524f6ca0b691e2e9b4b7bf/setup.py", line 65, in <module>
          Extension('MASShortcut._inlines',
        File "/private/var/folders/yl/ndrrqv712fs02p5sdtxhml7h0000gn/T/pip-install-k6y5qymk/pyobjc-masshortcut_e3ef160adc524f6ca0b691e2e9b4b7bf/pyobjc_setup.py", line 390, in Extension
          os_level = get_os_level()
        File "/private/var/folders/yl/ndrrqv712fs02p5sdtxhml7h0000gn/T/pip-install-k6y5qymk/pyobjc-masshortcut_e3ef160adc524f6ca0b691e2e9b4b7bf/pyobjc_setup.py", line 204, in get_os_level
          pl = plistlib.readPlist('/System/Library/CoreServices/SystemVersion.plist')
      AttributeError: module 'plistlib' has no attribute 'readPlist'
      [end of output]
```

See https://docs.python.org/3.9/whatsnew/3.9.html#removed
